import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/app-sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/shared/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-black text-white`}
      >
        <ClerkProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="min-h-screen w-full">
              <Navbar />
              <div className="w-full flex justify-center items-center">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
